### ISSUE TITLE
Noe overlapp med "projeksjoner.md" i veilledning01

### ISSUE THREAD

**Issue by spohner** [GeoForum/veiledning05#1]
Ser at temaet projeksjoner er dekket noe av "projeksjoner.md" i veiledning01.

**Comment by spohner** [comment]
Foreslår at denne artikkelen bruker "projeksjoner.md" som inspirasjon, og på lengre sikt dekker de sammen behovet for skriverier rundt dette temaet.

**Comment by ellvtr** [comment]
Bruker det ikke i v1, kan evt linke derfra til din

**Comment by ellvtr** [comment]
Du kan evt flytte filen over i v5

**Comment by spohner** [comment]
Det var en god idé, @ellvtr. Jeg har kopiert filen over i veil05.

**Comment by ellvtr** [comment]
OK, veiledning 1 peker nå hit på veiledning 5
